version: "3.8"
services:
  fir_pipeline:
    build:
      context: ./main_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
        - PORT=8000
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DB=${MYSQL_DB}
        - FIR_AUTH_KEY=${FIR_AUTH_KEY}

    depends_on:
      - gguf_model_server
      - asr_ocr_model_server

  gguf_model_server:
    build:
      context: ./gguf_model_server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MODEL_SERVER_PORT=8001

  asr_ocr_model_server:
    build:
      context: ./asr_ocr_model_server
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ASR_OCR_PORT=8002

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fir_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
